
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: catering
    ports: [ "5432:5432" ]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./db/02-reservations.sql:/docker-entrypoint-initdb.d/02-reservations.sql:ro
volumes:
  dbdata:
